import type {
  Customer,
  SupportPartner,
  SupportRequest,
  Match,
  JourneyMessage,
  Payment,
  OperationEvent,
  Issue,
  PartnerEarning,
  FinanceRecord,
  SupportCategory,
} from './types'

export const currentCustomer: Customer = {
  id: 'cust-1',
  name: 'Priya Sharma',
  phone: '+91 98765 43210',
  email: 'priya@example.com',
  preferences: {
    genderPreference: 'female',
    languagePreference: 'kannada',
  },
  trustedContacts: [
    { name: 'Rahul Sharma', phone: '+91 87654 32109', relationship: 'Brother' },
  ],
  repeatPartnerIds: ['partner-1'],
  createdAt: '2025-12-01T00:00:00Z',
}

export const supportPartners: SupportPartner[] = [
  {
    id: 'partner-1',
    name: 'Ameen Khan',
    photo: '',
    phone: '+91 99887 76655',
    email: 'ameen@withh.in',
    languages: ['kannada', 'english', 'hindi', 'urdu'],
    gender: 'male',
    completedJourneys: 213,
    verified: true,
    bio: 'Ameen has completed 213 support journeys and specializes in first-time visits and senior accompaniment.',
    specialties: ['Hospital Visits', 'Government Offices', 'Elderly Support'],
    available: true,
    rating: 4.9,
    joinedAt: '2025-06-01T00:00:00Z',
  },
  {
    id: 'partner-2',
    name: 'Kavitha Nair',
    photo: '',
    phone: '+91 88776 65544',
    email: 'kavitha@withh.in',
    languages: ['kannada', 'english', 'malayalam', 'tamil'],
    gender: 'female',
    completedJourneys: 187,
    verified: true,
    bio: 'Kavitha is a warm and empathetic companion who excels at helping women feel safe and supported during medical visits.',
    specialties: ['Hospital Visits', 'Women\'s Health', 'Interview Support'],
    available: true,
    rating: 4.8,
    joinedAt: '2025-07-15T00:00:00Z',
  },
  {
    id: 'partner-3',
    name: 'Sunil Raj',
    photo: '',
    phone: '+91 77665 54433',
    email: 'sunil@withh.in',
    languages: ['kannada', 'english', 'telugu', 'hindi'],
    gender: 'male',
    completedJourneys: 156,
    verified: true,
    bio: 'Sunil brings calm and reliability to every support journey, with extensive experience in government office visits.',
    specialties: ['Government Offices', 'Legal Appointments', 'Senior Support'],
    available: true,
    rating: 4.7,
    joinedAt: '2025-08-01T00:00:00Z',
  },
  {
    id: 'partner-4',
    name: 'Lakshmi Devi',
    photo: '',
    phone: '+91 66554 43322',
    email: 'lakshmi@withh.in',
    languages: ['kannada', 'english', 'hindi'],
    gender: 'female',
    completedJourneys: 94,
    verified: true,
    bio: 'Lakshmi is patient and compassionate, making her an ideal companion for elderly support and social situations.',
    specialties: ['Elderly Support', 'Events & Social', 'Hospital Visits'],
    available: true,
    rating: 4.9,
    joinedAt: '2025-09-20T00:00:00Z',
  },
]

export const supportRequests: SupportRequest[] = [
  {
    id: 'req-1',
    customerId: 'cust-1',
    whoNeedsSupport: 'me',
    category: 'hospital',
    meetingLocation: 'Home - 123, 1st Main, HSR Layout, Bangalore',
    destination: 'Apollo Hospital, Bannerghatta Road',
    date: '2026-06-08',
    time: '09:00',
    duration: '2-4',
    description: 'I have a follow-up appointment and feel anxious about going alone.',
    accessibilityNeeds: 'None',
    genderPreference: 'female',
    languagePreference: 'kannada',
    trustedContact: {
      name: 'Rahul Sharma',
      phone: '+91 87654 32109',
      relationship: 'Brother',
    },
    status: 'completed',
    assignedPartnerId: 'partner-2',
    matchId: 'match-1',
    createdAt: '2026-06-05T10:00:00Z',
    updatedAt: '2026-06-08T11:30:00Z',
  },
  {
    id: 'req-2',
    customerId: 'cust-1',
    whoNeedsSupport: 'me',
    category: 'government',
    meetingLocation: 'Home - 123, 1st Main, HSR Layout, Bangalore',
    destination: 'BBMP Office, HSR Layout',
    date: '2026-06-12',
    time: '10:00',
    duration: 'under-2',
    description: 'Need to get documents attested. First time doing this alone.',
    accessibilityNeeds: 'None',
    genderPreference: 'no-preference',
    languagePreference: 'english',
    status: 'finding-partner',
    createdAt: '2026-06-06T14:00:00Z',
    updatedAt: '2026-06-06T14:30:00Z',
  },
  {
    id: 'req-3',
    customerId: 'cust-1',
    whoNeedsSupport: 'me',
    category: 'interview',
    meetingLocation: 'Home - 123, 1st Main, HSR Layout, Bangalore',
    destination: 'WeWork, HSR Layout, Sector 3',
    date: '2026-06-15',
    time: '14:00',
    duration: '2-4',
    description: 'I have an important job interview. Would appreciate someone to wait nearby for moral support.',
    accessibilityNeeds: 'None',
    genderPreference: 'no-preference',
    languagePreference: 'english',
    status: 'submitted',
    createdAt: '2026-06-07T09:00:00Z',
    updatedAt: '2026-06-07T09:00:00Z',
  },
]

export const matches: Match[] = [
  {
    id: 'match-1',
    requestId: 'req-1',
    partnerId: 'partner-2',
    customerId: 'cust-1',
    status: 'confirmed',
    matchedAt: '2026-06-05T14:00:00Z',
    confirmedAt: '2026-06-05T16:00:00Z',
    reasonForMatch: [
      'Matches preference for female support partner',
      'Speaks Kannada and English as requested',
      'Has extensive hospital visit experience',
      'Previously completed support journey with customer',
    ],
    customerApproved: true,
  },
]

export const journeyMessages: Record<string, JourneyMessage[]> = {
  'req-1': [
    {
      id: 'msg-1',
      requestId: 'req-1',
      from: 'system',
      senderName: 'WITHH',
      content: 'Your support request has been received.',
      timestamp: '2026-06-05T10:00:00Z',
    },
    {
      id: 'msg-2',
      requestId: 'req-1',
      from: 'system',
      senderName: 'WITHH',
      content: 'We are reviewing your request and finding the right Support Partner.',
      timestamp: '2026-06-05T11:00:00Z',
    },
    {
      id: 'msg-3',
      requestId: 'req-1',
      from: 'system',
      senderName: 'WITHH',
      content: 'Kavitha has been assigned to your support journey.',
      timestamp: '2026-06-05T14:00:00Z',
    },
    {
      id: 'msg-4',
      requestId: 'req-1',
      from: 'system',
      senderName: 'WITHH',
      content: 'Your support journey with Kavitha is confirmed.',
      timestamp: '2026-06-05T16:00:00Z',
    },
    {
      id: 'msg-5',
      requestId: 'req-1',
      from: 'partner',
      senderName: 'Kavitha',
      content: 'Hello Priya! I\'ll be there at 9 AM. I\'ll be wearing a blue saree and will wait near the main entrance.',
      timestamp: '2026-06-05T17:00:00Z',
    },
    {
      id: 'msg-6',
      requestId: 'req-1',
      from: 'customer',
      senderName: 'Priya',
      content: 'Thank you Kavitha! I\'ll be ready at the meeting point.',
      timestamp: '2026-06-05T17:30:00Z',
    },
    {
      id: 'msg-7',
      requestId: 'req-1',
      from: 'system',
      senderName: 'WITHH',
      content: 'Kavitha is on her way to the meeting location.',
      timestamp: '2026-06-08T08:30:00Z',
    },
    {
      id: 'msg-8',
      requestId: 'req-1',
      from: 'system',
      senderName: 'WITHH',
      content: 'Kavitha has arrived at the meeting location.',
      timestamp: '2026-06-08T08:55:00Z',
    },
    {
      id: 'msg-9',
      requestId: 'req-1',
      from: 'system',
      senderName: 'WITHH',
      content: 'Support journey is in progress.',
      timestamp: '2026-06-08T09:05:00Z',
    },
    {
      id: 'msg-10',
      requestId: 'req-1',
      from: 'system',
      senderName: 'WITHH',
      content: 'Support journey completed. Thank you for choosing WITHH.',
      timestamp: '2026-06-08T11:30:00Z',
    },
  ],
  'req-2': [
    {
      id: 'msg-11',
      requestId: 'req-2',
      from: 'system',
      senderName: 'WITHH',
      content: 'Your support request has been received.',
      timestamp: '2026-06-06T14:00:00Z',
    },
    {
      id: 'msg-12',
      requestId: 'req-2',
      from: 'system',
      senderName: 'WITHH',
      content: 'We are finding the right Support Partner for your BBMP office visit.',
      timestamp: '2026-06-06T14:30:00Z',
    },
  ],
  'req-3': [
    {
      id: 'msg-13',
      requestId: 'req-3',
      from: 'system',
      senderName: 'WITHH',
      content: 'Your support request has been received.',
      timestamp: '2026-06-07T09:00:00Z',
    },
  ],
}

export const payments: Payment[] = [
  {
    id: 'pay-1',
    requestId: 'req-1',
    customerId: 'cust-1',
    amount: 899,
    baseFee: 899,
    additionalTimeFee: 0,
    status: 'completed',
    createdAt: '2026-06-05T16:30:00Z',
    completedAt: '2026-06-05T16:35:00Z',
  },
]

export const operationEvents: Record<string, OperationEvent[]> = {
  'req-1': [
    {
      id: 'oe-1',
      requestId: 'req-1',
      type: 'status-change',
      content: 'Request reviewed and approved. Starting partner matching.',
      operatorName: 'Anjali (Ops)',
      timestamp: '2026-06-05T11:30:00Z',
    },
    {
      id: 'oe-2',
      requestId: 'req-1',
      type: 'note',
      content: 'Customer prefers Kannada-speaking female partner. Kavitha Nair is available and has high rating.',
      operatorName: 'Anjali (Ops)',
      timestamp: '2026-06-05T12:00:00Z',
    },
    {
      id: 'oe-3',
      requestId: 'req-1',
      type: 'status-change',
      content: 'Kavitha Nair assigned. Awaiting customer confirmation.',
      operatorName: 'Anjali (Ops)',
      timestamp: '2026-06-05T14:00:00Z',
    },
    {
      id: 'oe-4',
      requestId: 'req-1',
      type: 'status-change',
      content: 'Customer confirmed. Payment completed. Support confirmed.',
      operatorName: 'System',
      timestamp: '2026-06-05T16:35:00Z',
    },
  ],
}

export const issues: Issue[] = []

export const partnerEarnings: PartnerEarning[] = [
  {
    id: 'earn-1',
    partnerId: 'partner-2',
    requestId: 'req-1',
    amount: 499,
    status: 'paid',
    paidAt: '2026-06-10T00:00:00Z',
    createdAt: '2026-06-08T11:30:00Z',
  },
]

export const financeRecords: FinanceRecord[] = [
  {
    id: 'fin-1',
    requestId: 'req-1',
    customerPayment: 899,
    partnerPayout: 499,
    revenue: 400,
    status: 'completed',
    createdAt: '2026-06-08T11:30:00Z',
  },
]

export const categoryLabels: Record<SupportCategory, string> = {
  hospital: 'Hospital Visit',
  government: 'Government Office Visit',
  interview: 'Interview / Important Meeting',
  elderly: 'Elderly Support',
  event: 'Event / Social Situation',
  other: 'Other',
}

export const categoryIcons: Record<SupportCategory, string> = {
  hospital: '🏥',
  government: '🏛️',
  interview: '💼',
  elderly: '👴',
  event: '🎉',
  other: '📋',
}

export const pricing = {
  standardSupport: 699,
  sensitiveSupport: 899,
  additionalTime: 199,
}
